name: make

on:
  push:
    branches:
      - "**"
    paths: ["**"]

jobs:
  cpp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run make
        run: |
          make
